import { Helmet } from 'react-helmet-async';

export default function TermsPage() {
  return (
    <>
      <Helmet><title>Terms of Service - Yunai Academy</title></Helmet>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <div className="prose prose-gray max-w-none space-y-6 text-gray-600">
          <p className="text-sm text-gray-400">Last updated: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using Yunai Academy ("the Platform"), you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">2. Account Registration</h2>
            <p>You must register for an account to access certain features. You agree to provide accurate information and keep your credentials secure. You are responsible for all activity under your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">3. Use of Services</h2>
            <p>The Platform provides educational content including video courses, quizzes, AI tutoring, and community features for CA exam preparation. Content is for personal, non-commercial educational use only.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">4. Intellectual Property</h2>
            <p>All content on the Platform is owned by Yunai Academy or its content creators. You may not reproduce, distribute, or create derivative works without explicit permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">5. AI Tutor Disclaimer</h2>
            <p>The AI Tutor provides educational assistance but is not a substitute for professional advice. Responses are generated by AI and may contain inaccuracies. Always verify important information with official sources.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">6. Community Guidelines</h2>
            <p>Users must be respectful in community interactions. Spam, harassment, plagiarism, and sharing of copyrighted exam material is strictly prohibited.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">7. Limitation of Liability</h2>
            <p>Yunai Academy is provided "as is" without warranties. We are not liable for any damages arising from use of the Platform, including exam results or career outcomes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">8. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:legal@yunaiacademy.com" className="text-primary-600 hover:text-primary-700">legal@yunaiacademy.com</a>.</p>
          </section>
        </div>
      </div>
    </>
  );
}
